import { FormEvent, useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { gameApi } from "../api/gameApi";
import type { EnergySource, Habitat, Species, SpeciesInput, SpeciesType, Strategy, Traits } from "../types/api";
import { AsyncState } from "./AsyncState";
import { usePolling } from "./usePolling";

const traitNames: (keyof Traits)[] = ["thermal_tolerance", "radiation_tolerance", "ph_tolerance", "metabolic_efficiency", "reproduction_rate", "mutation_rate", "energy_efficiency", "structural_resistance"];
const initialTraits = Object.fromEntries(traitNames.map(name => [name, 12])) as unknown as Traits;
const n = (value: number, digits = 1) => Number(value ?? 0).toLocaleString("pt-BR", { maximumFractionDigits: digits });

function Title({ children }: { children: string }) { return <><p className="eyebrow">Eos-1</p><h1>{children}</h1></>; }
function Stat({ label, value }: { label: string; value: string | number }) { return <div className="stat"><small>{label}</small><strong>{value}</strong></div>; }
function SpeciesCard({ species }: { species: Species }) { const ownership = species.is_player_controlled ? "SUA ESPÉCIE" : species.status === "WILD" ? "WILD · AUTÔNOMA" : species.status === "EXTINCT" ? "EXTINTA" : "OUTRA ESPÉCIE"; return <article className={`card ${species.is_player_controlled ? "player-species" : ""}`}><div className="row"><h3>{species.name}</h3><span className={`badge ${species.status.toLowerCase()}`}>{ownership}</span></div><p>{species.species_type} · {species.strategy}</p><div className="stats"><Stat label="População" value={n(species.population, 0)} /><Stat label="Fitness" value={n(species.fitness, 2)} /><Stat label="Geração" value={n(species.generation, 0)} /></div>{species.status === "WILD" && <p className="warning">Esta linhagem evolui autonomamente.</p>}{!species.is_player_controlled && species.status !== "WILD" && <p className="muted">Esta espécie não está sob seu controle.</p>}{species.is_player_controlled && <p className="accent">Sua espécie</p>}<Link to={`/species/${species.id}`}>Ver espécie →</Link></article>; }

export function Dashboard() {
  const world = usePolling(gameApi.world); const current = usePolling(async () => { try { return await gameApi.currentSpecies(); } catch (e: any) { if (e.status === 404) return null; throw e; } });
  const events = usePolling(() => gameApi.events(5)); const species = usePolling(gameApi.worldSpecies);
  return <section className="page"><Title>Dashboard</Title><AsyncState {...world}>{w => <><div className="stats hero"><Stat label="Geração global" value={n(w.generation, 0)} /><Stat label="Temperatura" value={`${n(w.temperature)}°`} /><Stat label="O₂" value={n(w.oxygen, 2)} /><Stat label="CO₂" value={n(w.co2, 2)} /><Stat label="Espécies vivas" value={w.species_alive} /><Stat label="Extintas" value={w.species_extinct} /></div>{w.dev_mode && <DevTools onDone={world.retry} />}</>}</AsyncState><h2>Minha espécie</h2><AsyncState {...current}>{s => s ? <><SpeciesCard species={s} /><Link className="button" to={`/species/${s.id}`}>Abrir minha espécie</Link></> : <div className="panel onboarding"><h2>Sua linhagem ainda não começou</h2><p>Você ainda não controla nenhuma espécie em Eos-1. Crie uma espécie para começar sua história evolutiva.</p><Link className="button" to="/species/create">Criar minha espécie</Link></div>}</AsyncState><div className="columns"><div><h2>Eventos recentes</h2><AsyncState {...events} empty={x => !x.items.length}>{x => <div className="list">{x.items.map(e => <article key={e.id}><strong>{e.name}</strong><small>Geração {n(e.generation, 0)} · {e.rarity}</small></article>)}</div>}</AsyncState></div><div><h2>Atividade mundial</h2><AsyncState {...species} empty={x => !x.items.length}>{x => <div className="list">{x.items.slice(0, 6).map(s => <article key={s.id}><strong>{s.name}</strong><small>{s.is_player_controlled ? "SUA ESPÉCIE" : s.status === "WILD" ? "WILD · autônoma" : "Outra espécie"} · pop. {n(s.population, 0)}</small></article>)}</div>}</AsyncState></div></div></section>;
}

function DevTools({ onDone }: { onDone: () => void }) { const [busy, setBusy] = useState(false); const run = async (ticks: number) => { setBusy(true); try { await gameApi.simulate(ticks); onDone(); } finally { setBusy(false); } }; return <div className="panel"><h2>DEV Tools</h2><div className="actions">{[1, 10, 100, 1000].map(x => <button disabled={busy} key={x} onClick={() => void run(x)}>+{x} tick{x > 1 ? "s" : ""}</button>)}</div></div>; }

export function CreateSpecies() {
  const habitats = usePolling(gameApi.habitats); const navigate = useNavigate();
  const [input, setInput] = useState<SpeciesInput>({ name: "", species_type: "AUTOTROPH", energy_source: "SOLAR", strategy: "COLONIZER", habitat_id: 0, traits: initialTraits });
  const [preview, setPreview] = useState<any>(null); const [error, setError] = useState(""); const points = Object.values(input.traits).reduce((a, b) => a + b, 0);
  const change = (key: keyof SpeciesInput, value: unknown) => { setInput({ ...input, [key]: value }); setPreview(null); };
  const changeType = (value: SpeciesType) => { setInput(current => ({ ...current, species_type: value, energy_source: value === "PARASITIC" ? "PARASITIC" : current.energy_source === "PARASITIC" ? "SOLAR" : current.energy_source, strategy: value === "PARASITIC" ? "PARASITE" : current.strategy === "PARASITE" ? "COLONIZER" : current.strategy })); setPreview(null); };
  useEffect(() => {
    const items = habitats.data?.items ?? [];
    if (items.length && !items.some(h => h.id === input.habitat_id))
      setInput(current => ({ ...current, habitat_id: items[0].id }));
  }, [habitats.data, input.habitat_id]);
  const submit = async (e: FormEvent) => { e.preventDefault(); setError(""); try { const created = await gameApi.createSpecies(input); navigate(`/species/${created.id}`); } catch (x) { setError(x instanceof Error ? x.message : "Falha ao criar"); } };
  const previewNow = async () => { setError(""); try { setPreview(await gameApi.previewSpecies(input)); } catch (x) { setError(x instanceof Error ? x.message : "Preview falhou"); } };
  const loadingHabitats = habitats.loading; const emptyHabitats = !loadingHabitats && !(habitats.data?.items.length); const over = Math.max(0, points - 100);
  return <section className="page"><Title>Criar espécie</Title><p className="lede">1. Configure sua espécie · 2. Analise a viabilidade · 3. Crie sua espécie.</p><form className="panel form" onSubmit={submit}><label>Nome<input required value={input.name} onChange={e => change("name", e.target.value)} /></label><div className="form-grid"><Select label="Tipo" value={input.species_type} options={["AUTOTROPH","CHEMOSYNTHETIC","HETEROTROPH","PARASITIC"]} onChange={x => changeType(x as SpeciesType)} /><Select label="Energia" value={input.energy_source} options={input.species_type === "PARASITIC" ? ["PARASITIC"] : ["SOLAR","CHEMICAL","ORGANIC"]} onChange={x => change("energy_source", x as EnergySource)} /><Select label="Estratégia" value={input.strategy} options={input.species_type === "PARASITIC" ? ["PARASITE"] : ["COLONIZER","COMPETITOR","RESISTANT","OPPORTUNIST"]} onChange={x => change("strategy", x as Strategy)} /><label>Habitat{loadingHabitats ? <span>Carregando habitats…</span> : emptyHabitats ? <span className="danger">Nenhum habitat disponível.</span> : <select value={input.habitat_id} onChange={e => change("habitat_id", Number(e.target.value))}>{habitats.data?.items.map(h => <option key={h.id} value={h.id}>{h.name}</option>)}</select>}</label></div><h2>Pontos restantes: <span className={over ? "danger" : points === 100 ? "accent" : "warning"}>{100 - points}</span></h2>{over > 0 && <p className="danger">Você excedeu o limite de traits em {over} pontos.</p>}<div className="traits">{traitNames.map(name => <label key={name}>{name.replaceAll("_", " ")} <b>{input.traits[name]}</b><input type="range" min="0" max="100" value={input.traits[name]} onChange={e => { setInput({ ...input, traits: { ...input.traits, [name]: Number(e.target.value) } }); setPreview(null); }} /></label>)}</div><p className="muted">Analise a viabilidade antes de confirmar sua espécie.</p>{error && <p className="danger">{error}</p>}<div className="actions"><button type="button" disabled={!input.name || points > 100 || !input.habitat_id || loadingHabitats || emptyHabitats} onClick={() => void previewNow()}>Analisar viabilidade</button><button disabled={!preview || points > 100 || loadingHabitats || emptyHabitats}>Criar espécie</button></div>{!preview && <small>Faça a análise de viabilidade para liberar a criação.</small>}{preview && <div className="preview"><Stat label="Fitness estimado" value={n(preview.estimated_fitness, 2)} /><Stat label="Tendência" value={preview.estimated_growth} /><Stat label="Risco" value={preview.risk} /><Stat label="Compatibilidade" value={n(preview.environment_compatibility, 2)} /></div>}</form></section>;
}
function Select({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (v: string) => void }) { return <label>{label}<select value={value} onChange={e => onChange(e.target.value)}>{options.map(x => <option key={x}>{x}</option>)}</select></label>; }

export function SpeciesDetail() {
  const id = Number(useParams().id); const state = usePolling(() => gameApi.speciesById(id)); const habitats = usePolling(gameApi.habitats); const evolutions = usePolling(() => gameApi.evolutions(id)); const pressures = usePolling(() => gameApi.pressures(id)); const [destination, setDestination] = useState(0); const [error, setError] = useState("");
  useEffect(() => {
    const candidates = (habitats.data?.items ?? []).filter(h => h.id !== state.data?.habitat_id);
    if (candidates.length && !candidates.some(h => h.id === destination)) setDestination(candidates[0].id);
  }, [habitats.data, state.data?.habitat_id, destination]);
  const act = async (fn: () => Promise<unknown>) => { setError(""); try { await fn(); await state.retry(); await evolutions.retry(); } catch (x) { setError(x instanceof Error ? x.message : "Ação falhou"); } };
  return <section className="page"><Title>Espécie</Title><AsyncState {...state}>{s => <><SpeciesCard species={s}/>{s.resources && <div className="panel"><h2>Estado fisiológico</h2><div className="stats">{Object.entries(s.resources).map(([k,v]) => <Stat key={k} label={k.replaceAll("_", " ")} value={`${n(v,0)}${s.resource_rates?.[k as keyof typeof s.resource_rates] !== undefined ? ` (+${n(s.resource_rates[k as keyof typeof s.resource_rates],0)}/tick)` : ""}`} />)}</div></div>}<div className="panel"><h2>Pressões atuais</h2><AsyncState {...pressures} empty={x => !x.items.length}>{x => <div className="list">{x.items.map(p => <article key={p.type}><strong>{p.type} · {p.severity}</strong><small>{p.description} ({n(p.score,2)})</small></article>)}</div>}</AsyncState></div><div className="panel"><h2>Traits</h2><div className="stats">{traitNames.map(t => <Stat key={t} label={t.replaceAll("_", " ")} value={s.traits[t]} />)}</div></div>{s.is_player_controlled && <><div className="panel"><h2>Respostas adaptativas</h2><AsyncState {...evolutions}>{x => <div className="list">{x.items.map(e => <article key={e.id}><strong>{e.name}</strong><small>{e.pressure?.type ? `Pressão: ${e.pressure.type}` : "Resposta geral"} · {e.duration_ticks} ticks · {e.status ?? "disponível"}</small>{!e.status && <button disabled={e.available === false} onClick={() => void act(() => gameApi.startEvolution(id, e.id))}>{e.available === false ? "Indisponível" : "Favorecer adaptação"}</button>}</article>)}</div>}</AsyncState></div><div className="panel form"><h2>Ações rápidas</h2><label>Destino<select value={destination} onChange={e => setDestination(Number(e.target.value))}>{habitats.data?.items.filter(h => h.id !== s.habitat_id).map(h => <option key={h.id} value={h.id}>{h.name}</option>)}</select></label><div className="actions"><button onClick={() => void act(() => gameApi.migrate(id, destination))}>Migrar população inteira</button><button onClick={() => void act(() => gameApi.split(id))}>Expedição fundadora</button><button onClick={() => void act(() => gameApi.focusReproduction(id))}>Foco reprodução</button><button onClick={() => void act(() => gameApi.focusSurvival(id))}>Foco sobrevivência</button><button className="danger-button" onClick={() => confirm("Abandonar espécie?") && void act(() => gameApi.abandon(id))}>Abandonar</button></div><Select label="Alterar estratégia" value={s.strategy} options={["COLONIZER","COMPETITOR","RESISTANT","OPPORTUNIST","PARASITE"]} onChange={v => void act(() => gameApi.changeStrategy(id, v as Strategy))}/>{error && <p className="danger">{error}</p>}</div></>}</>}</AsyncState></section>;
}

export function WorldPage() { const world = usePolling(gameApi.world); const habitats = usePolling(gameApi.habitats); const species = usePolling(gameApi.worldSpecies); return <section className="page"><Title>Mundo</Title><AsyncState {...world}>{w => <div className="stats hero"><Stat label="Planeta" value={w.name}/><Stat label="Geração" value={n(w.generation,0)}/><Stat label="Água" value={n(w.water_availability)}/><Stat label="Energia solar" value={n(w.solar_energy)}/><Stat label="Energia química" value={n(w.chemical_energy)}/><Stat label="Atividade geológica" value={n(w.geological_activity)}/></div>}</AsyncState><h2>Habitats</h2><AsyncState {...habitats}>{x => <div className="cards">{x.items.map(h => <HabitatCard key={h.id} habitat={h}/>)}</div>}</AsyncState><h2>Espécies</h2><AsyncState {...species} empty={x => !x.items.length}>{x => <div className="cards">{x.items.map(s => <SpeciesCard key={s.id} species={s}/>)}</div>}</AsyncState></section>; }
function HabitatCard({ habitat: h }: { habitat: Habitat }) { return <article className="card"><h3>{h.name}</h3><p>{n(h.temperature)}° · pH {n(h.ph)} · capacidade {n(h.carrying_capacity,0)}</p></article>; }

export function HistoryPage() { const state = usePolling(gameApi.worldHistory); return <Timeline title="História do mundo" state={state} />; }
export function EventsPage() { const state = usePolling(gameApi.events); return <section className="page"><Title>Eventos</Title><AsyncState {...state} empty={x => !x.items.length}>{x => <div className="timeline">{x.items.map(e => <article key={e.id}><span className="badge">{e.rarity}</span><h3>{e.name}</h3><p>{e.description}</p><small>Geração {n(e.generation,0)}</small></article>)}</div>}</AsyncState></section>; }
function Timeline({ title, state }: { title: string; state: ReturnType<typeof usePolling<any>> }) { return <section className="page"><Title>{title}</Title><AsyncState {...state} empty={x => !x.items.length}>{x => <div className="timeline">{x.items.map((e: any, i: number) => <article key={`${e.kind}-${e.generation}-${i}`}><small>Geração {n(e.generation,0)} · {e.kind}</small><h3>{e.title}</h3><p>{e.description}</p></article>)}</div>}</AsyncState></section>; }
export function LegacyPage() { const state = usePolling(gameApi.legacy); return <section className="page"><Title>Legado de Zero</Title><AsyncState {...state}>{x => <><div className="stats hero"><Stat label="Criadas" value={x.total_species}/><Stat label="Ativas" value={x.active}/><Stat label="WILD" value={x.wild}/><Stat label="Extintas" value={x.extinct}/><Stat label="População viva" value={n(x.total_population,0)}/><Stat label="World Firsts" value={x.world_firsts.length}/></div><div className="cards">{x.species.map(s => <SpeciesCard key={s.id} species={s}/>)}</div></>}</AsyncState></section>; }
