import { FormEvent, useEffect, useState } from "react";
import { Link, useLocation, useNavigate, useOutletContext, useParams } from "react-router-dom";
import { gameApi } from "../api/gameApi";
import type { EnergySource, Evolution, SelectivePressure, Species, SpeciesInput, SpeciesType, Strategy, Traits } from "../types/api";
import { AsyncState } from "./AsyncState";
import { usePolling } from "./usePolling";
import type { ShellContext } from "./AppShell";

const traitNames: (keyof Traits)[] = ["thermal_tolerance", "radiation_tolerance", "ph_tolerance", "metabolic_efficiency", "reproduction_rate", "mutation_rate", "energy_efficiency", "structural_resistance"];
const initialTraits = Object.fromEntries(traitNames.map(name => [name, 12])) as unknown as Traits;
const n = (value: number, digits = 1) => Number(value ?? 0).toLocaleString("pt-BR", { maximumFractionDigits: digits });
const blockedReason: Record<string, string> = { PRESSURE_INSUFFICIENT: "Pressão insuficiente.", RESPONSE_ACTIVE: "Indisponível enquanto outra resposta adaptativa está ativa.", INSUFFICIENT_RESOURCES: "Recursos insuficientes.", REQUIREMENTS_NOT_MET: "Requisitos não atendidos.", SPECIES_NOT_CONTROLLED: "Espécie não controlada." };
const traitLabel: Record<keyof Traits, string> = { thermal_tolerance: "Tolerância térmica", radiation_tolerance: "Radiação", ph_tolerance: "pH", metabolic_efficiency: "Metabolismo", reproduction_rate: "Reprodução", mutation_rate: "Mutação", energy_efficiency: "Energia", structural_resistance: "Estrutura" };

function Title({ children }: { children: string }) { return <div className="page-title"><p className="eyebrow">Eos-1 · centro evolutivo</p><h1>{children}</h1></div>; }
function Stat({ label, value }: { label: string; value: string | number }) { return <div className="stat"><small>{label}</small><strong>{value}</strong></div>; }
export function Dashboard() {
  const { species: current, world } = useOutletContext<ShellContext>();
  const events = usePolling(() => gameApi.events(5)); const species = usePolling(gameApi.worldSpecies);
  return <section className="page"><Title>Visão geral</Title>{world && <div className="world-strip"><Stat label="Geração global" value={n(world.generation, 0)}/><Stat label="Temperatura" value={`${n(world.temperature)}°`}/><Stat label="O₂" value={n(world.oxygen, 2)}/><Stat label="CO₂" value={n(world.co2, 2)}/><Stat label="Vivas" value={world.species_alive}/>{world.dev_mode && <DevTools onDone={() => location.reload()}/>}</div>}{current ? <LineageOverview species={current}/> : <div className="onboarding bio-hero"><div className="cell-glyph"/><div><p className="eyebrow">LINHAGEM AUSENTE</p><h2>Sua história evolutiva ainda não começou</h2><p>Crie uma espécie para intervir nas pressões seletivas de Eos-1.</p><Link className="button" to="/species/create">Criar minha espécie</Link></div></div>}<div className="overview-grid"><section><SectionTitle>Atividade recente</SectionTitle><AsyncState {...events} empty={x => !x.items.length} emptyMessage="Nenhum evento registrado.">{x => <div className="compact-list">{x.items.map(e => <article key={e.id}><span className="badge">{e.rarity}</span><strong>{e.name}</strong><small>Geração {n(e.generation, 0)}</small></article>)}</div>}</AsyncState></section><section><SectionTitle>Ecossistema ativo</SectionTitle><AsyncState {...species} empty={x => !x.items.length}>{x => <div className="compact-list">{x.items.slice(0, 6).map(s => <article key={s.id}><span className={`status-dot ${s.status.toLowerCase()}`}/><strong>{s.name}</strong><small>{s.is_player_controlled ? "SUA LINHAGEM" : s.status} · {n(s.population, 0)}</small></article>)}</div>}</AsyncState></section></div></section>;
}

function LineageOverview({ species }: { species: Species }) {
  const pressures = usePolling(() => gameApi.pressures(species.id)); const evolutions = usePolling(() => gameApi.evolutions(species.id));
  const active = evolutions.data?.items.find(e => e.status === "IN_PROGRESS");
  return <><div className="lineage-hero"><div className="cell-glyph"><i/></div><div><p className="eyebrow">SUA LINHAGEM</p><h2>{species.name}</h2><p>{species.species_type} · {species.strategy} · {species.status}</p><div className="inline-metrics"><b>{n(species.population,0)} população</b><b>{n(species.fitness,2)} fitness</b><b>geração {n(species.generation,0)}</b></div><Link className="button" to={`/species/${species.id}`}>Abrir linhagem</Link></div></div><div className="overview-grid"><section><SectionTitle>Pressões atuais</SectionTitle><AsyncState {...pressures} empty={x => !x.items.length} emptyMessage="Nenhuma pressão relevante no momento.">{x => <PressureList items={x.items}/>}</AsyncState></section><section><SectionTitle>Processo adaptativo</SectionTitle>{active ? <ProcessCard response={active}/> : <div className="empty-compact">Nenhuma resposta ativa.</div>}</section></div></>;
}

function SectionTitle({ children }: { children: string }) { return <h2 className="section-header">{children}</h2>; }

function DevTools({ onDone }: { onDone: () => void }) { const [busy, setBusy] = useState(false); const run = async (ticks: number) => { setBusy(true); try { await gameApi.simulate(ticks); onDone(); } finally { setBusy(false); } }; return <div className="panel"><h2>DEV Tools</h2><div className="actions">{[1, 10, 100, 1000].map(x => <button disabled={busy} key={x} onClick={() => void run(x)}>+{x} tick{x > 1 ? "s" : ""}</button>)}</div></div>; }

export function CreateSpecies() {
  const habitats = usePolling(gameApi.habitats); const navigate = useNavigate(); const { refreshSpecies } = useOutletContext<ShellContext>();
  const [input, setInput] = useState<SpeciesInput>({ name: "", species_type: "AUTOTROPH", energy_source: "SOLAR", strategy: "COLONIZER", habitat_id: 0, traits: initialTraits });
  const [preview, setPreview] = useState<any>(null); const [error, setError] = useState(""); const points = Object.values(input.traits).reduce((a, b) => a + b, 0);
  const change = (key: keyof SpeciesInput, value: unknown) => { setInput({ ...input, [key]: value }); setPreview(null); };
  const changeType = (value: SpeciesType) => { setInput(current => ({ ...current, species_type: value, energy_source: value === "PARASITIC" ? "PARASITIC" : current.energy_source === "PARASITIC" ? "SOLAR" : current.energy_source, strategy: value === "PARASITIC" ? "PARASITE" : current.strategy === "PARASITE" ? "COLONIZER" : current.strategy })); setPreview(null); };
  useEffect(() => {
    const items = habitats.data?.items ?? [];
    if (items.length && !items.some(h => h.id === input.habitat_id))
      setInput(current => ({ ...current, habitat_id: items[0].id }));
  }, [habitats.data, input.habitat_id]);
  const submit = async (e: FormEvent) => { e.preventDefault(); setError(""); try { const created = await gameApi.createSpecies(input); await refreshSpecies(); navigate(`/species/${created.id}`); } catch (x) { setError(x instanceof Error ? x.message : "Falha ao criar"); } };
  const previewNow = async () => { setError(""); try { setPreview(await gameApi.previewSpecies(input)); } catch (x) { setError(x instanceof Error ? x.message : "Preview falhou"); } };
  const loadingHabitats = habitats.loading; const emptyHabitats = !loadingHabitats && !(habitats.data?.items.length); const over = Math.max(0, points - 100);
  return <section className="page"><Title>Criar espécie</Title><p className="lede">1. Configure sua espécie · 2. Analise a viabilidade · 3. Crie sua espécie.</p><form className="panel form" onSubmit={submit}><label>Nome<input required value={input.name} onChange={e => change("name", e.target.value)} /></label><div className="form-grid"><Select label="Tipo" value={input.species_type} options={["AUTOTROPH","CHEMOSYNTHETIC","HETEROTROPH","PARASITIC"]} onChange={x => changeType(x as SpeciesType)} /><Select label="Energia" value={input.energy_source} options={input.species_type === "PARASITIC" ? ["PARASITIC"] : ["SOLAR","CHEMICAL","ORGANIC"]} onChange={x => change("energy_source", x as EnergySource)} /><Select label="Estratégia" value={input.strategy} options={input.species_type === "PARASITIC" ? ["PARASITE"] : ["COLONIZER","COMPETITOR","RESISTANT","OPPORTUNIST"]} onChange={x => change("strategy", x as Strategy)} /><label>Habitat{loadingHabitats ? <span>Carregando habitats…</span> : emptyHabitats ? <span className="danger">Nenhum habitat disponível.</span> : <select value={input.habitat_id} onChange={e => change("habitat_id", Number(e.target.value))}>{habitats.data?.items.map(h => <option key={h.id} value={h.id}>{h.name}</option>)}</select>}</label></div><h2>Pontos restantes: <span className={over ? "danger" : points === 100 ? "accent" : "warning"}>{100 - points}</span></h2>{over > 0 && <p className="danger">Você excedeu o limite de traits em {over} pontos.</p>}<div className="traits">{traitNames.map(name => <label key={name}>{name.replaceAll("_", " ")} <b>{input.traits[name]}</b><input type="range" min="0" max="100" value={input.traits[name]} onChange={e => { setInput({ ...input, traits: { ...input.traits, [name]: Number(e.target.value) } }); setPreview(null); }} /></label>)}</div><p className="muted">Analise a viabilidade antes de confirmar sua espécie.</p>{error && <p className="danger">{error}</p>}<div className="actions"><button type="button" disabled={!input.name || points > 100 || !input.habitat_id || loadingHabitats || emptyHabitats} onClick={() => void previewNow()}>Analisar viabilidade</button><button disabled={!preview || points > 100 || loadingHabitats || emptyHabitats}>Criar espécie</button></div>{!preview && <small>Faça a análise de viabilidade para liberar a criação.</small>}{preview && <div className="preview"><Stat label="Fitness estimado" value={n(preview.estimated_fitness, 2)} /><Stat label="Tendência" value={preview.estimated_growth} /><Stat label="Risco" value={preview.risk} /><Stat label="Compatibilidade" value={n(preview.environment_compatibility, 2)} /></div>}</form></section>;
}
function Select({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (v: string) => void }) { return <label>{label}<select value={value} onChange={e => onChange(e.target.value)}>{options.map(x => <option key={x}>{x}</option>)}</select></label>; }

export function SpeciesDetail() {
  const id = Number(useParams().id); const location = useLocation(); const { refreshSpecies } = useOutletContext<ShellContext>(); const state = usePolling(() => gameApi.speciesById(id)); const habitats = usePolling(gameApi.habitats); const evolutions = usePolling(() => gameApi.evolutions(id)); const pressures = usePolling(() => gameApi.pressures(id)); const [destination, setDestination] = useState(0); const [error, setError] = useState("");
  useEffect(() => { if (state.data && location.hash) document.getElementById(location.hash.slice(1))?.scrollIntoView(); }, [location.hash, state.data]);
  useEffect(() => {
    const candidates = (habitats.data?.items ?? []).filter(h => h.id !== state.data?.habitat_id);
    if (candidates.length && !candidates.some(h => h.id === destination)) setDestination(candidates[0].id);
  }, [habitats.data, state.data?.habitat_id, destination]);
  const act = async (fn: () => Promise<unknown>) => { setError(""); try { await fn(); await Promise.all([state.retry(), evolutions.retry(), pressures.retry(), refreshSpecies()]); } catch (x) { setError(x instanceof Error ? x.message : "Ação falhou"); } };
  return <section className="page"><Title>{state.data?.is_player_controlled ? "Minha linhagem" : "Linhagem observada"}</Title><AsyncState {...state}>{s => <>
    <div className="lineage-summary"><div className="cell-glyph"><i/></div><div><p className="eyebrow">{s.is_player_controlled ? "SUA LINHAGEM" : s.status}</p><h2>{s.name}</h2><p>{s.species_type} · {s.strategy}</p></div><div className="inline-metrics"><b>{n(s.population,0)} população</b><b>{n(s.fitness,2)} fitness</b><b>geração {n(s.generation,0)}</b><b>{habitats.data?.items.find(h => h.id === s.habitat_id)?.name ?? "Habitat"}</b></div></div>
    {s.resources && <section className="system-section"><SectionTitle>Estado fisiológico</SectionTitle><div className="physiology-grid">{Object.entries(s.resources).map(([key,value]) => <div key={key}><small>{key === "genetic_material" ? "Reserva genética" : key.replaceAll("_", " ")}</small><strong>{n(value,0)}</strong>{s.resource_rates?.[key as keyof typeof s.resource_rates] !== undefined && <span>+{n(s.resource_rates[key as keyof typeof s.resource_rates],0)}/tick</span>}</div>)}</div></section>}
    <section id="pressures" className="system-section"><SectionTitle>Pressões</SectionTitle><AsyncState {...pressures} empty={x => !x.items.length} emptyMessage="Nenhuma pressão relevante. A linhagem está ajustada ao habitat atual.">{x => <PressureList items={x.items}/>}</AsyncState></section>
    {s.is_player_controlled && <section className="system-section"><SectionTitle>Respostas adaptativas</SectionTitle><AsyncState {...evolutions}>{x => <AdaptiveResponses items={x.items} start={evolutionId => act(() => gameApi.startEvolution(id, evolutionId))}/>}</AsyncState></section>}
    <section id="genome" className="system-section"><SectionTitle>Genoma</SectionTitle><Genome traits={s.traits}/></section>
    {s.is_player_controlled && <section className="system-section"><SectionTitle>Ações rápidas</SectionTitle><div className="action-groups"><div><h3>Adaptação tática</h3><button onClick={() => void act(() => gameApi.focusReproduction(id))}>Foco reprodução</button><button onClick={() => void act(() => gameApi.focusSurvival(id))}>Foco sobrevivência</button></div><div><h3>Movimento</h3><label>Destino<select value={destination} onChange={e => setDestination(Number(e.target.value))}>{habitats.data?.items.filter(h => h.id !== s.habitat_id).map(h => <option key={h.id} value={h.id}>{h.name}</option>)}</select></label><button disabled={!destination} onClick={() => void act(() => gameApi.migrate(id, destination))}>Migrar população inteira</button><button onClick={() => void act(() => gameApi.split(id))}>Expedição fundadora</button><small>Uma fração enfrenta efeito fundador e altera aleatoriamente parte da distribuição genética.</small></div><div><h3>Comportamento</h3><Select label="Estratégia atual" value={s.strategy} options={["COLONIZER","COMPETITOR","RESISTANT","OPPORTUNIST","PARASITE"]} onChange={v => void act(() => gameApi.changeStrategy(id, v as Strategy))}/></div><div className="risk-zone"><h3>Risco</h3><button className="danger-button" onClick={() => confirm("Abandonar espécie?") && void act(() => gameApi.abandon(id))}>Abandonar linhagem</button></div></div>{error && <p className="inline-error">{error}</p>}</section>}
    <section className="system-section"><SectionTitle>Histórico evolutivo</SectionTitle><EvolutionHistory species={s}/></section>
  </>}</AsyncState></section>;
}

function PressureList({ items }: { items: SelectivePressure[] }) { return <div className="pressure-list">{items.map(p => <article className={`pressure-row severity-${p.severity.toLowerCase()}`} key={p.type}><strong>{p.type.replaceAll("_", " ")}</strong><span className="severity-label">{p.severity}</span><p>{p.description}</p><small>intensidade {n(p.score,2)}</small></article>)}</div>; }

function ProcessCard({ response }: { response: Evolution }) { return <article className="process-card"><span className="pulse"/><div><small>RESPOSTA ATIVA</small><strong>{response.name}</strong><span>{response.ticks_remaining} ticks restantes</span></div><dl><dt>Viés seletivo</dt><dd>{String(response.selection_bias?.trait).replaceAll("_", " ")} +{n(Number(response.selection_bias?.strength) * 100,0)}%</dd><dt>Trade-off</dt><dd>reprodução ×{response.tradeoffs?.reproduction_modifier ?? 1}</dd></dl></article>; }

function AdaptiveResponses({ items, start }: { items: Evolution[]; start: (id: string) => Promise<unknown> }) {
  const active = items.find(item => item.status === "IN_PROGRESS"); const available = items.filter(item => item.status !== "IN_PROGRESS" && item.can_start); const blocked = items.filter(item => item.status !== "IN_PROGRESS" && !item.can_start);
  return <div className="response-groups">{active && <><h3>Ativa</h3><ProcessCard response={active}/></>}<h3>Disponíveis</h3>{available.length ? <div className="response-list">{available.map(item => <ResponseRow key={item.id} item={item} start={start}/>)}</div> : <div className="empty-compact">Nenhuma resposta pode ser iniciada agora.</div>}<h3>Bloqueadas</h3><div className="response-list blocked">{blocked.map(item => <ResponseRow key={item.id} item={item} start={start}/>)}</div></div>;
}

function ResponseRow({ item, start }: { item: Evolution; start: (id: string) => Promise<unknown> }) { return <article><div><strong>{item.name}</strong><small>{item.pressure?.type?.replaceAll("_", " ")} · {item.duration_ticks} ticks</small>{item.status === "COMPLETED" && <small>Usada anteriormente</small>}</div><div><small>Custo fisiológico</small><span>{Object.entries(item.cost).map(([key,value]) => `${key.replaceAll("_", " ")} ${value}`).join(" · ")}</span>{item.blocked_reason && <small className="warning">{blockedReason[item.blocked_reason]}</small>}</div><button disabled={!item.can_start} onClick={() => void start(item.id)}>{item.status === "COMPLETED" ? "Favorecer novamente" : "Favorecer"}</button></article>; }

function Genome({ traits }: { traits: Traits }) { const total = Object.values(traits).reduce((sum,value) => sum + value, 0); return <><div className="genome-load"><span>Carga genética</span><strong>{total} / 100</strong></div><div className="genome-list">{traitNames.map(trait => <div className="genome-row" key={trait}><span>{traitLabel[trait]}</span><b>{traits[trait]}</b><div><i style={{ width: `${traits[trait]}%` }}/></div></div>)}</div></>; }

function EvolutionHistory({ species }: { species: Species }) { const snapshots = species.population_history ?? []; const current = snapshots[0]?.population; const previous = snapshots[1]?.population; const trend = current !== undefined && previous ? ((current - previous) / previous) * 100 : null; return <div className="history-grid"><div><h3>Tendência populacional</h3>{trend === null ? <p className="muted">Dados insuficientes.</p> : <div className="trend"><strong>{trend >= 0 ? "+" : ""}{n(trend,1)}%</strong><span>{n(previous!,0)} → {n(current!,0)}</span></div>}</div><div><h3>Alterações recentes</h3><div className="compact-list">{species.trait_history?.slice(0,8).map((change,index) => <article key={`${change.generation}-${change.trait}-${index}`}><strong>{traitLabel[change.trait]}</strong><span>{change.old_value} → {change.new_value}</span><small>{change.cause} · geração {n(change.generation,0)}</small></article>)}{!species.trait_history?.length && <p className="muted">Nenhuma alteração registrada.</p>}</div></div></div>; }

export function WorldPage() {
  const world = usePolling(gameApi.world); const habitats = usePolling(gameApi.habitats); const species = usePolling(gameApi.worldSpecies);
  const habitatNames = new Map(habitats.data?.items.map(h => [h.id, h.name]));
  return <section className="page"><Title>Ecossistema</Title><AsyncState {...world}>{w => <div className="world-strip"><Stat label="Ambiente" value={w.name}/><Stat label="Geração" value={n(w.generation,0)}/><Stat label="Água" value={n(w.water_availability)}/><Stat label="Energia solar" value={n(w.solar_energy)}/><Stat label="Energia química" value={n(w.chemical_energy)}/><Stat label="Atividade geológica" value={n(w.geological_activity)}/></div>}</AsyncState>
    <section className="system-section"><SectionTitle>Habitats</SectionTitle><AsyncState {...habitats}>{x => <div className="table-wrap"><table className="data-table"><thead><tr><th>Habitat</th><th>Temp.</th><th>Rad.</th><th>pH</th><th>Solar</th><th>Química</th><th>Orgânico</th><th>Capacidade</th></tr></thead><tbody>{x.items.map(h => <tr key={h.id}><th>{h.name}</th><td>{n(h.temperature)}</td><td>{n(h.radiation)}</td><td>{n(h.ph)}</td><td>{n(h.solar_energy)}</td><td>{n(h.chemical_energy)}</td><td>{n(h.organic_resources)}</td><td>{n(h.carrying_capacity,0)}</td></tr>)}</tbody></table></div>}</AsyncState></section>
    <section className="system-section"><SectionTitle>Linhagens presentes</SectionTitle><AsyncState {...species} empty={x => !x.items.length}>{x => <div className="table-wrap"><table className="data-table species-table"><thead><tr><th>Linhagem</th><th>Status</th><th>População</th><th>Fitness</th><th>Habitat</th></tr></thead><tbody>{x.items.map(s => <tr className={s.is_player_controlled ? "player-row" : ""} key={s.id}><th><Link to={`/species/${s.id}`}>{s.name}</Link>{s.is_player_controlled && <span className="you-label">VOCÊ</span>}</th><td><span className={`badge ${s.status.toLowerCase()}`}>{s.status}</span></td><td>{n(s.population,0)}</td><td>{n(s.fitness,2)}</td><td>{habitatNames.get(s.habitat_id) ?? `#${s.habitat_id}`}</td></tr>)}</tbody></table></div>}</AsyncState></section>
  </section>;
}

export function HistoryPage() { const state = usePolling(gameApi.worldHistory); return <Timeline title="História do mundo" state={state} />; }
export function EventsPage() { const state = usePolling(gameApi.events); return <section className="page"><Title>Eventos</Title><AsyncState {...state} empty={x => !x.items.length} emptyMessage="Nenhum evento registrado.">{x => <div className="timeline">{x.items.map(e => <article key={e.id}><div className="timeline-marker"/><div><small>Geração {n(e.generation,0)}</small><h3>{e.name}</h3><p>{e.description}</p></div><span className="badge">{e.rarity}</span></article>)}</div>}</AsyncState></section>; }
function Timeline({ title, state }: { title: string; state: ReturnType<typeof usePolling<any>> }) { return <section className="page"><Title>{title}</Title><AsyncState {...state} empty={x => !x.items.length}>{x => <div className="timeline">{x.items.map((e: any, i: number) => <article key={`${e.kind}-${e.generation}-${i}`}><div className="timeline-marker"/><div><small>Geração {n(e.generation,0)} · {e.kind}</small><h3>{e.title}</h3><p>{e.description}</p></div></article>)}</div>}</AsyncState></section>; }
export function LegacyPage() { const state = usePolling(gameApi.legacy); return <section className="page"><Title>Legado de Zero</Title><AsyncState {...state}>{x => <><div className="world-strip"><Stat label="Linhagens criadas" value={x.total_species}/><Stat label="Ativas" value={x.active}/><Stat label="WILD" value={x.wild}/><Stat label="Extintas" value={x.extinct}/><Stat label="População viva" value={n(x.total_population,0)}/><Stat label="World Firsts" value={x.world_firsts.length}/></div><section className="system-section"><SectionTitle>Linhagens</SectionTitle><div className="table-wrap"><table className="data-table species-table"><thead><tr><th>Linhagem</th><th>Tipo</th><th>Status</th><th>População</th><th>Fitness</th><th>Geração</th></tr></thead><tbody>{x.species.map(s => <tr key={s.id}><th><Link to={`/species/${s.id}`}>{s.name}</Link></th><td>{s.species_type}</td><td><span className={`badge ${s.status.toLowerCase()}`}>{s.status}</span></td><td>{n(s.population,0)}</td><td>{n(s.fitness,2)}</td><td>{n(s.generation,0)}</td></tr>)}</tbody></table></div></section></>}</AsyncState></section>; }
