from enum import StrEnum


class SpeciesType(StrEnum):
    AUTOTROPH = "AUTOTROPH"; CHEMOSYNTHETIC = "CHEMOSYNTHETIC"; HETEROTROPH = "HETEROTROPH"; PARASITIC = "PARASITIC"
class SpeciesStatus(StrEnum):
    ACTIVE = "ACTIVE"; WILD = "WILD"; EXTINCT = "EXTINCT"
class EnergySource(StrEnum):
    SOLAR = "SOLAR"; CHEMICAL = "CHEMICAL"; ORGANIC = "ORGANIC"; PARASITIC = "PARASITIC"
class Strategy(StrEnum):
    COLONIZER = "COLONIZER"; COMPETITOR = "COMPETITOR"; RESISTANT = "RESISTANT"; OPPORTUNIST = "OPPORTUNIST"; PARASITE = "PARASITE"
class TraitChangeCause(StrEnum):
    MUTATION = "MUTATION"; SELECTION = "SELECTION"; FOUNDER_EFFECT = "FOUNDER_EFFECT"; ENVIRONMENTAL_PRESSURE = "ENVIRONMENTAL_PRESSURE"; EVENT = "EVENT"
class RelationType(StrEnum):
    COMPETITION = "COMPETITION"; PARASITISM = "PARASITISM"
class EventRarity(StrEnum):
    COMMON = "COMMON"; UNCOMMON = "UNCOMMON"; RARE = "RARE"; LEGENDARY = "LEGENDARY"; WORLD_FIRST = "WORLD_FIRST"
class ActionType(StrEnum):
    MIGRATE = "MIGRATE"; SPLIT_POPULATION = "SPLIT_POPULATION"; CHANGE_STRATEGY = "CHANGE_STRATEGY"; FOCUS_REPRODUCTION = "FOCUS_REPRODUCTION"; FOCUS_SURVIVAL = "FOCUS_SURVIVAL"; ABANDON_SPECIES = "ABANDON_SPECIES"
class ActionStatus(StrEnum):
    PENDING = "PENDING"; COMPLETED = "COMPLETED"; FAILED = "FAILED"
