"""Frozen initial persistent game schema.

Revision ID: 0001_initial_schema
Revises: None
"""
from alembic import op
import sqlalchemy as sa

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("worlds", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(80), nullable=False, unique=True), sa.Column("generation", sa.Integer(), nullable=False), sa.Column("tick", sa.Integer(), nullable=False), sa.Column("temperature", sa.Float(), nullable=False), sa.Column("oxygen", sa.Float(), nullable=False), sa.Column("co2", sa.Float(), nullable=False), sa.Column("radiation", sa.Float(), nullable=False), sa.Column("water_availability", sa.Float(), nullable=False), sa.Column("average_ph", sa.Float(), nullable=False), sa.Column("solar_energy", sa.Float(), nullable=False), sa.Column("chemical_energy", sa.Float(), nullable=False), sa.Column("geological_activity", sa.Float(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("players", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("username", sa.String(80), nullable=False, unique=True), sa.Column("is_bot", sa.Boolean(), nullable=False), sa.Column("bot_kind", sa.String(40)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("habitats", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("world_id", sa.Integer(), sa.ForeignKey("worlds.id", ondelete="CASCADE"), nullable=False), sa.Column("name", sa.String(80), nullable=False), *[sa.Column(n, sa.Float(), nullable=False) for n in ("temperature", "radiation", "ph", "water", "solar_energy", "chemical_energy", "organic_resources")], sa.Column("carrying_capacity", sa.Integer(), nullable=False), sa.CheckConstraint("carrying_capacity > 0"), sa.UniqueConstraint("world_id", "name")); op.create_index("ix_habitats_world_id", "habitats", ["world_id"])
    traits = ("thermal_tolerance", "radiation_tolerance", "ph_tolerance", "metabolic_efficiency", "reproduction_rate", "mutation_rate", "energy_efficiency", "structural_resistance")
    op.create_table("species", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(100), nullable=False), sa.Column("creator_id", sa.Integer(), sa.ForeignKey("players.id"), nullable=False), sa.Column("habitat_id", sa.Integer(), sa.ForeignKey("habitats.id"), nullable=False), sa.Column("species_type", sa.String(16), nullable=False), sa.Column("status", sa.String(8), nullable=False), sa.Column("is_player_controlled", sa.Boolean(), nullable=False), sa.Column("population", sa.Integer(), nullable=False), sa.Column("generation", sa.Integer(), nullable=False), sa.Column("fitness", sa.Float(), nullable=False), sa.Column("strategy", sa.String(16), nullable=False), sa.Column("energy_source", sa.String(16), nullable=False), *[sa.Column(n, sa.Integer(), nullable=False) for n in traits], sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("abandoned_at", sa.DateTime(timezone=True)), sa.Column("extinct_at", sa.DateTime(timezone=True)), sa.CheckConstraint("population >= 0", name="ck_species_population_nonnegative"), sa.CheckConstraint(" AND ".join(f"{n} BETWEEN 0 AND 100" for n in traits), name="ck_species_traits_range"), sa.CheckConstraint(" + ".join(traits) + " <= 100", name="ck_species_trait_budget"), sa.CheckConstraint("species_type != 'PARASITIC' OR (energy_source = 'PARASITIC' AND strategy = 'PARASITE')", name="ck_species_parasite_configuration"), sa.CheckConstraint("is_player_controlled IS FALSE OR status = 'ACTIVE'", name="ck_species_controlled_is_active"), sa.CheckConstraint("status != 'EXTINCT' OR (is_player_controlled IS FALSE AND population = 0)", name="ck_species_extinct_state")); op.create_index("ix_species_creator_id", "species", ["creator_id"]); op.create_index("ix_species_habitat_id", "species", ["habitat_id"]); op.create_index("uq_species_one_controlled_per_player", "species", ["creator_id"], unique=True, postgresql_where=sa.text("is_player_controlled IS TRUE"), sqlite_where=sa.text("is_player_controlled = 1"))
    op.create_table("world_snapshots", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("world_id", sa.Integer(), sa.ForeignKey("worlds.id", ondelete="CASCADE"), nullable=False), sa.Column("generation", sa.Integer(), nullable=False), sa.Column("tick", sa.Integer(), nullable=False), *[sa.Column(n, sa.Float(), nullable=False) for n in ("temperature", "oxygen", "co2", "radiation")], sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("world_id", "tick")); op.create_index("ix_world_snapshots_world_id", "world_snapshots", ["world_id"])
    op.create_table("species_population_snapshots", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("species_id", sa.Integer(), sa.ForeignKey("species.id", ondelete="CASCADE"), nullable=False), sa.Column("generation", sa.Integer(), nullable=False), sa.Column("population", sa.Integer(), nullable=False), sa.Column("fitness", sa.Float(), nullable=False), sa.Column("traits", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)); op.create_index("ix_species_population_snapshots_species_id", "species_population_snapshots", ["species_id"])
    op.create_table("species_trait_history", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("species_id", sa.Integer(), sa.ForeignKey("species.id", ondelete="CASCADE"), nullable=False), sa.Column("generation", sa.Integer(), nullable=False), sa.Column("trait", sa.String(40), nullable=False), sa.Column("old_value", sa.Integer(), nullable=False), sa.Column("new_value", sa.Integer(), nullable=False), sa.Column("cause", sa.String(24), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)); op.create_index("ix_species_trait_history_species_id", "species_trait_history", ["species_id"])
    op.create_table("species_relations", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("predator_or_parasite_id", sa.Integer(), sa.ForeignKey("species.id", ondelete="CASCADE"), nullable=False), sa.Column("target_species_id", sa.Integer(), sa.ForeignKey("species.id", ondelete="CASCADE"), nullable=False), sa.Column("relation_type", sa.String(16), nullable=False), sa.Column("strength", sa.Float(), nullable=False), sa.Column("infection_rate", sa.Float()), sa.Column("virulence", sa.Float()), sa.Column("transmission_rate", sa.Float()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.CheckConstraint("predator_or_parasite_id != target_species_id"), sa.UniqueConstraint("predator_or_parasite_id", "target_species_id", "relation_type")); op.create_index("ix_species_relations_predator_or_parasite_id", "species_relations", ["predator_or_parasite_id"]); op.create_index("ix_species_relations_target_species_id", "species_relations", ["target_species_id"])
    op.create_table("game_events", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("world_id", sa.Integer(), sa.ForeignKey("worlds.id"), nullable=False), sa.Column("code", sa.String(80), nullable=False), sa.Column("name", sa.String(120), nullable=False), sa.Column("description", sa.Text(), nullable=False), sa.Column("rarity", sa.String(16), nullable=False), sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=False), sa.Column("generation", sa.Integer(), nullable=False), sa.Column("historical", sa.Boolean(), nullable=False), sa.Column("global_unique", sa.Boolean(), nullable=False), sa.Column("species_id", sa.Integer(), sa.ForeignKey("species.id")), sa.Column("player_id", sa.Integer(), sa.ForeignKey("players.id")), sa.Column("metadata", sa.JSON(), nullable=False)); op.create_index("ix_game_events_world_id", "game_events", ["world_id"]); op.create_index("uq_game_event_world_global_code", "game_events", ["world_id", "code"], unique=True, postgresql_where=sa.text("global_unique IS TRUE"), sqlite_where=sa.text("global_unique = 1"))
    op.create_table("player_actions", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("player_id", sa.Integer(), sa.ForeignKey("players.id"), nullable=False), sa.Column("species_id", sa.Integer(), sa.ForeignKey("species.id"), nullable=False), sa.Column("action_type", sa.String(24), nullable=False), sa.Column("status", sa.String(12), nullable=False), sa.Column("payload", sa.JSON(), nullable=False), sa.Column("execute_at_tick", sa.Integer()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("completed_at", sa.DateTime(timezone=True))); op.create_index("ix_player_actions_player_id", "player_actions", ["player_id"]); op.create_index("ix_player_actions_species_id", "player_actions", ["species_id"])
    op.create_table("historical_flags", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("world_id", sa.Integer(), sa.ForeignKey("worlds.id"), nullable=False), sa.Column("species_id", sa.Integer(), sa.ForeignKey("species.id")), sa.Column("player_id", sa.Integer(), sa.ForeignKey("players.id")), sa.Column("code", sa.String(100), nullable=False), sa.Column("generation", sa.Integer(), nullable=False), sa.Column("metadata", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.CheckConstraint("species_id IS NULL OR player_id IS NULL", name="ck_historical_flag_single_subject")); op.create_index("ix_historical_flags_world_id", "historical_flags", ["world_id"]); op.create_index("ix_historical_flags_species_id", "historical_flags", ["species_id"]); op.create_index("ix_historical_flags_player_id", "historical_flags", ["player_id"]); op.create_index("uq_historical_flag_global", "historical_flags", ["world_id", "code"], unique=True, postgresql_where=sa.text("species_id IS NULL AND player_id IS NULL"), sqlite_where=sa.text("species_id IS NULL AND player_id IS NULL")); op.create_index("uq_historical_flag_species", "historical_flags", ["world_id", "species_id", "code"], unique=True, postgresql_where=sa.text("species_id IS NOT NULL AND player_id IS NULL"), sqlite_where=sa.text("species_id IS NOT NULL AND player_id IS NULL")); op.create_index("uq_historical_flag_player", "historical_flags", ["world_id", "player_id", "code"], unique=True, postgresql_where=sa.text("species_id IS NULL AND player_id IS NOT NULL"), sqlite_where=sa.text("species_id IS NULL AND player_id IS NOT NULL"))


def downgrade() -> None:
    for table in ("historical_flags", "player_actions", "game_events", "species_relations", "species_trait_history", "species_population_snapshots", "world_snapshots", "species", "habitats", "players", "worlds"):
        op.drop_table(table)
